name: Deploy 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: <DOCKERHUB_USERNAME>/ex3_2:latest

      - name: Deploy to Render.com
        uses: renderhq/github-action@1.3.0
        with:
          render_account_id: <RENDER_ACCOUNT_ID>
          render_token: ${{ secrets.RENDER_TOKEN }}
          render_yaml: render.yaml
          env: production
